name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - name: Allow unshare to create user namespaces
        run: |
          sudo cp .github/apparmor/nix-unshare /etc/apparmor.d/nix-unshare
          sudo apparmor_parser -r /etc/apparmor.d/nix-unshare
      - run: nix flake check -L

  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix fmt -- --ci
